import React from 'react';
import { useSetting } from '../db/hooks';

export default function InvoicePrintView({ invoice }) {
  // Use hook to get business profile
  const businessProfile = useSetting('businessProfile') || {};

  if (!invoice) return null;

  return (
    <div className="print-only fixed inset-0 bg-white z-[9999] text-black p-10 font-sans hidden">
      {/* Header */}
      <div className="flex justify-between items-start border-b-2 border-gray-200 pb-8 mb-8">
        <div>
          <h1 className="text-4xl font-extrabold text-gray-900 tracking-tight">INVOICE</h1>
          <p className="text-gray-500 mt-1 font-mono text-sm">{invoice.invoiceId || invoice.id}</p>
        </div>
        <div className="text-right">
          <h2 className="text-xl font-bold text-gray-800">{businessProfile.name || 'Your Business Name'}</h2>
          <p className="text-sm text-gray-500 mt-1">{businessProfile.email || 'email@example.com'}</p>
          <p className="text-sm text-gray-500">{businessProfile.phone || '+000 0000 0000'}</p>
        </div>
      </div>

      {/* Bill To & Details */}
      <div className="flex justify-between mb-12">
        <div>
          <p className="text-sm font-bold text-gray-400 uppercase tracking-wider mb-2">Billed To</p>
          <p className="text-lg font-bold text-gray-800">{invoice.customer}</p>
        </div>
        <div className="text-right">
          <p className="text-sm font-bold text-gray-400 uppercase tracking-wider mb-2">Date Issued</p>
          <p className="text-lg font-semibold text-gray-800">{invoice.date}</p>
        </div>
      </div>

      {/* Items Table */}
      <table className="w-full mb-12">
        <thead>
          <tr className="border-b-2 border-gray-200">
            <th className="py-3 text-left text-sm font-bold text-gray-600 uppercase tracking-wider">Description</th>
            <th className="py-3 text-right text-sm font-bold text-gray-600 uppercase tracking-wider">Total</th>
          </tr>
        </thead>
        <tbody>
          <tr className="border-b border-gray-100">
            <td className="py-6 text-gray-800 font-medium">{invoice.items}</td>
            <td className="py-6 text-right font-bold text-gray-900 text-lg">{invoice.amount}</td>
          </tr>
        </tbody>
      </table>

      {/* Footer / Total */}
      <div className="flex justify-between items-end border-t-2 border-gray-800 pt-8 mt-12">
        <div className="max-w-xs">
          <p className="text-sm font-bold text-gray-400 uppercase tracking-wider mb-2">Payment Info</p>
          <p className="text-sm text-gray-700 font-medium whitespace-pre-wrap">
            {businessProfile.bank || 'Bank Account Details Not Provided'}
          </p>
        </div>
        <div className="text-right">
          <p className="text-sm font-bold text-gray-400 uppercase tracking-wider mb-2">Amount Due</p>
          <p className="text-4xl font-black text-gray-900">{invoice.amount}</p>
        </div>
      </div>
      
      <div className="mt-16 text-center text-sm text-gray-400 font-medium">
        Thank you for your business! Generated by Casjoe Offline AI.
      </div>
    </div>
  );
}
